{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "6cac6004",
   "metadata": {},
   "source": [
    "#### Streamlit code "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8f2eb396",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import libraries\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from PIL import Image\n",
    "from google_currency import convert\n",
    "import pandas as pd\n",
    "import requests\n",
    "import cv2\n",
    "from streamlit_functions import *\n",
    "import json\n",
    "import os\n",
    "import pytesseract"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c1fe4f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "# To make things easier later, we're also importing numpy and pandas for\n",
    "# working with sample data.\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from PIL import Image\n",
    "from google_currency import convert\n",
    "import pandas as pd\n",
    "import requests\n",
    "import cv2\n",
    "from streamlit_functions import *\n",
    "import time\n",
    "import json\n",
    "import streamlit as st\n",
    "import os\n",
    "\n",
    "\n",
    "imagen = Image.open(\"bann.JPG\")\n",
    "st.image(imagen)\n",
    "st.markdown('**Convert currencies from pictures!**:sunglasses:')\n",
    "\n",
    "\n",
    "st.sidebar.markdown('**:one:Input options**:rocket:')\n",
    "currency_list = ['AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP', 'HKD', 'HRK', 'HUF', 'IDR', 'ILS',\n",
    "                 'INR', 'ISK', 'JPY', 'KRW', 'MXN', 'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'RON', 'RUB', 'SEK', 'SGD',\n",
    "                 'THB', 'TRY', 'USD', 'ZAR']\n",
    "\n",
    "input_price = st.sidebar.selectbox('Select base currency', currency_list)\n",
    "if len(input_price) == 0 or input_price == \"Select base currency\":\n",
    "    st.write(\"Please select currency\")\n",
    "\n",
    "\n",
    "output_price = st.sidebar.selectbox('Select target currency', currency_list)\n",
    "if len(output_price) == 0 or output_price == \"Select target currency\":\n",
    "    st.write(\"Please select currency\")\n",
    "\n",
    "st.sidebar.markdown(':two: :camera:')\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload image\", type = ['jpeg', 'jpg', 'png'])\n",
    "\n",
    "if uploaded_file:\n",
    "    #st.write('File successfully uploaded')\n",
    "    img = Image.open(uploaded_file)\n",
    "    img.save('imagenes/a.jpg')\n",
    "    st.write('**This is your image!**:zap:')\n",
    "    st.image(img)\n",
    "    #if st.button('converting'):\n",
    "\n",
    "    # os.system('open analisis')\n",
    "    # cv2.imwrite('analisis1',img)\n",
    "    image1 = cv2.imread('imagenes/a.jpg')\n",
    "    # transformacion a escala de grises\n",
    "    gray = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)\n",
    "    # Creamos copia de la imagen de entrada\n",
    "    image_aux = gray.copy()\n",
    "    try:\n",
    "        x=pytesseract.image_to_string(image_aux).split(\"\\n\")[0].replace(\",\",\".\")\n",
    "        y = float(x)\n",
    "        status_text = st.empty()\n",
    "        for i in range(100):\n",
    "            time.sleep(0.0001)\n",
    "        status_text.text('thinking')\n",
    "        st.balloons()\n",
    "\n",
    "        yas = converter(input_price, output_price, y)\n",
    "        st.write('**Converted!**:money_with_wings:')\n",
    "        st.write(yas)\n",
    "    except:\n",
    "         st.write(\"sorry, couldn't read image, try again!:ghost:\")\n",
    "    #st.write(x)\n",
    "\n",
    "#---------------------------------#\n",
    "# About\n",
    "expander_bar = st.beta_expander(\"About\")\n",
    "expander_bar.markdown(\"\"\"\n",
    "* **Python libraries:** streamlit, pandas, pillow, numpy, requests, json, pytesseract, google_currency, OpenCV\n",
    "* **Credit:** App built by Blanca Ribas Pombo\n",
    "* **Github:** https://github.com/BlancaRibas\n",
    "* ** Ironhack Final Project, June 2021\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8093204a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#functions\n",
    "\n",
    "def translate_picture (image):\n",
    "    \"\"\"Transformar imagen con formato imagen(jpg/png) en valor\"\"\"\n",
    "\n",
    "    return valor\n",
    "\n",
    "\n",
    "\n",
    "def converter (input_curr,output_currency,quantity):\n",
    "    c = convert(f'{input_curr}', f'{output_currency}', float(quantity))\n",
    "    x = json.loads(c)\n",
    "    return (x.get(\"amount\"))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "clase",
   "language": "python",
   "name": "clase"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
